/**
 * @brief   Action Definition (elgo_control <-> elgo_remote)
 */
export const ACTION = {
    NONE_ACTION: 'NONE',
    DEVICE_LOGIN: 'DEVICE_LOGIN',
    UPDATE_WIFI_LIST: 'UPDATE_WIFI_LIST',
    CONNECT_WIFI: "CONNECT_WIFI",
    MANAGE_DEVICE: 'MANAGE_DEVICE',
    ROTATE_DISPLAY: 'ROTATE_DISPLAY',
    DEVICE_OPTIONS: 'DEVICE_OPTIONS',
    USER_LOGIN: 'USER_LOGIN'
}